version: '3.8'

services:
  # Event Registration App
  event-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: event-registration-app
    ports:
      - "3000:80"
    environment:
      # Supabase Configuration
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
      - VITE_SUPABASE_SERVICE_ROLE_KEY=${VITE_SUPABASE_SERVICE_ROLE_KEY}
      
      # WhatsApp Configuration (if needed)
      - WHATSAPP_ACCESS_TOKEN=${WHATSAPP_ACCESS_TOKEN}
      - WHATSAPP_PHONE_NUMBER_ID=${WHATSAPP_PHONE_NUMBER_ID}
      - WHATSAPP_TEMPLATE_NAME=${WHATSAPP_TEMPLATE_NAME:-ticket_beautiful}
      - WHATSAPP_LANGUAGE_CODE=${WHATSAPP_LANGUAGE_CODE:-id}
      
      # Email Service
      - RESEND_API_KEY=${RESEND_API_KEY}
      
      # Rate Limiting
      - WHATSAPP_RATE_LIMIT_PER_MINUTE=${WHATSAPP_RATE_LIMIT_PER_MINUTE:-250}
      - WHATSAPP_RATE_LIMIT_PER_HOUR=${WHATSAPP_RATE_LIMIT_PER_HOUR:-1000}
    volumes:
      - ./logs:/var/log/nginx
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Development version (optional)
  event-app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: event-registration-app-dev
    ports:
      - "8080:8080"
    environment:
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
      - VITE_SUPABASE_SERVICE_ROLE_KEY=${VITE_SUPABASE_SERVICE_ROLE_KEY}
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    profiles:
      - dev

networks:
  default:
    name: event-registration-network 