version: '3.8'

services:
  # Event Registration App - Production
  event-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Supabase Configuration
        - VITE_SUPABASE_URL=${VITE_SUPABASE_URL:-https://placeholder.supabase.co}
        - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY:-placeholder-key}
        - VITE_SUPABASE_SERVICE_ROLE_KEY=${VITE_SUPABASE_SERVICE_ROLE_KEY}
        - VITE_APP_ENV=${VITE_APP_ENV:-production}
    container_name: event-registration-app
    ports:
      - "3000:80"
    environment:
      # Runtime environment variables (for edge functions if needed)
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
      - VITE_SUPABASE_SERVICE_ROLE_KEY=${VITE_SUPABASE_SERVICE_ROLE_KEY}
      - VITE_APP_ENV=${VITE_APP_ENV:-production}
      
      # WhatsApp Configuration (if needed)
      - WHATSAPP_ACCESS_TOKEN=${WHATSAPP_ACCESS_TOKEN}
      - WHATSAPP_PHONE_NUMBER_ID=${WHATSAPP_PHONE_NUMBER_ID}
      - WHATSAPP_TEMPLATE_NAME=${WHATSAPP_TEMPLATE_NAME:-ticket_beautiful}
      - WHATSAPP_LANGUAGE_CODE=${WHATSAPP_LANGUAGE_CODE:-id}
      
      # Email Service
      - RESEND_API_KEY=${RESEND_API_KEY}
      
      # Rate Limiting
      - WHATSAPP_RATE_LIMIT_PER_MINUTE=${WHATSAPP_RATE_LIMIT_PER_MINUTE:-250}
      - WHATSAPP_RATE_LIMIT_PER_HOUR=${WHATSAPP_RATE_LIMIT_PER_HOUR:-1000}
    volumes:
      - ./logs:/var/log/nginx
      - event-app-data:/usr/share/nginx/html
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --tries=1 --spider http://localhost/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /var/cache/nginx
      - /var/run

  # Development version
  event-app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: event-registration-app-dev
    ports:
      - "8080:8080"
    environment:
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
      - VITE_SUPABASE_SERVICE_ROLE_KEY=${VITE_SUPABASE_SERVICE_ROLE_KEY}
      - VITE_APP_ENV=${VITE_APP_ENV:-development}
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
      - event-app-dev-data:/app/.vite
    restart: unless-stopped
    profiles:
      - dev
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'

  # Nginx reverse proxy (optional for production)
  nginx-proxy:
    image: nginx:alpine
    container_name: event-app-nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/nginx.conf:ro
      - ./logs/nginx:/var/log/nginx
      - event-app-ssl:/etc/nginx/ssl
    depends_on:
      - event-app
    restart: unless-stopped
    profiles:
      - production
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.25'

volumes:
  event-app-data:
    driver: local
  event-app-dev-data:
    driver: local
  event-app-ssl:
    driver: local

networks:
  default:
    name: event-registration-network
    driver: bridge 