// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || "https://mjolfjoqfnszvvlbzhjn.supabase.co";
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1qb2xmam9xZm5zenZ2bGJ6aGpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4MzY0MzUsImV4cCI6MjA2ODQxMjQzNX0.vqMB_6wR2Jdx0mNKoNa-is2LS5pIAVrsQRQVkuSxdwg";

// Create Supabase client
export const supabase = createClient(supabaseUrl, supabaseAnonKey, {
  auth: {
    persistSession: true,
    storageKey: 'event-brite-maker-auth',
    storage: typeof window !== 'undefined' ? window.localStorage : null,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce'
  },
  db: {
    schema: 'public'
  },
  global: {
    headers: {
      'Content-Type': 'application/json',
    },
  }
});