// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mjolfjoqfnszvvlbzhjn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1qb2xmam9xZm5zenZ2bGJ6aGpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4MzY0MzUsImV4cCI6MjA2ODQxMjQzNX0.vqMB_6wR2Jdx0mNKoNa-is2LS5pIAVrsQRQVkuSxdwg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});